version: '3.8'

services:
  frontend:
    build: .
    ports:
      - '4173:4173'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - json-server

  json-server:
    image: clue/json-server
    volumes:
      - ./db.json:/data/db.json
    ports:
      - '5001:80'
    command: --watch /data/db.json
