import { CompanyId } from '@/common/types';
import { CompanyData } from '@/common/interfaces';

export const companiesDataInfo: Record<CompanyId, CompanyData> = {
  AAPL: {
    ticker: 'AAPL',
    name: 'Apple Inc',
    legalName: 'Apple Inc.',
    stockExchange: 'Nasdaq',
    shortDescription:
      'Apple designs and manufactures smartphones, computers, and accessories.',
    longDescription:
      'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories. It also provides services like Apple Music, Apple Arcade, and Apple Pay.',
    web: 'apple.com',
    businessAddress: 'One Apple Park Way, Cupertino, CA, 95014',
    businessPhone: '(408) 996-1010',
    entityLegalForm: 'INCORPORATED',
    latestFilingDate: '2024-05-02',
    incCountry: 'USA',
    employees: 164000,
    sector: 'Technology',
    industryCategory: 'Electronics',
    industryGroup: 'Diversified Electronics',
    firstStockPriceDate: '1980-12-12',
    lastStockPriceDate: '2024-08-01',
    legacySector: 'Technology',
    legacyIndustryCategory: 'Consumer Electronics',
    legacyIndustryGroup: 'Mobile Devices',
    mosaicPositioning: {
      defaultVisible: true,
      initialOrder: 1,
      zIndex: 10,
    },
  },
  NVDA: {
    ticker: 'NVDA',
    name: 'NVIDIA Corporation',
    legalName: 'NVIDIA Corporation',
    stockExchange: 'Nasdaq',
    shortDescription: 'NVIDIA develops graphics processing units and AI software.',
    longDescription:
      'NVIDIA develops GPUs, AI systems, and software products for gaming, professional visualization, data centers, and automotive markets.',
    web: 'nvidia.com',
    businessAddress: '2788 San Tomas Expressway, Santa Clara, CA, 95051',
    businessPhone: '(408) 486-2000',
    entityLegalForm: 'INCORPORATED',
    latestFilingDate: '2024-04-30',
    incCountry: 'USA',
    employees: 23000,
    sector: 'Technology',
    industryCategory: 'Semiconductors',
    industryGroup: 'Semiconductor Products',
    firstStockPriceDate: '1999-01-20',
    lastStockPriceDate: '2024-07-01',
    legacySector: 'Technology',
    legacyIndustryCategory: 'Semiconductors',
    legacyIndustryGroup: 'Graphics Processors',
    mosaicPositioning: {
      defaultVisible: true,
      initialOrder: 2,
      zIndex: 9,
    },
  },
  MSFT: {
    ticker: 'MSFT',
    name: 'Microsoft Corporation',
    legalName: 'Microsoft Corporation',
    stockExchange: 'Nasdaq',
    shortDescription: 'Microsoft develops software, services, and hardware.',
    longDescription:
      'Microsoft develops, licenses, and supports software products like Windows, Office, and Azure, along with hardware like Surface and Xbox.',
    web: 'microsoft.com',
    businessAddress: 'One Microsoft Way, Redmond, WA, 98052',
    businessPhone: '(425) 882-8080',
    entityLegalForm: 'INCORPORATED',
    latestFilingDate: '2024-05-01',
    incCountry: 'USA',
    employees: 181000,
    sector: 'Technology',
    industryCategory: 'Software & IT Services',
    industryGroup: 'Cloud Computing',
    firstStockPriceDate: '1986-03-13',
    lastStockPriceDate: '2024-06-15',
    legacySector: 'Technology',
    legacyIndustryCategory: 'Software',
    legacyIndustryGroup: 'Enterprise Software',
    mosaicPositioning: {
      defaultVisible: true,
      initialOrder: 3,
      zIndex: 8,
    },
  },
  GOOGL: {
    ticker: 'GOOGL',
    name: 'Alphabet Inc.',
    legalName: 'Alphabet Inc.',
    stockExchange: 'Nasdaq',
    shortDescription:
      'Alphabet provides internet services through Google and other companies.',
    longDescription:
      'Alphabet, the parent company of Google, is involved in internet services, cloud computing, artificial intelligence, and various other industries.',
    web: 'alphabet.com',
    businessAddress: '1600 Amphitheatre Parkway, Mountain View, CA, 94043',
    businessPhone: '(650) 253-0000',
    entityLegalForm: 'INCORPORATED',
    latestFilingDate: '2024-06-05',
    incCountry: 'USA',
    employees: 156500,
    sector: 'Technology',
    industryCategory: 'Internet Services',
    industryGroup: 'Search Engines',
    firstStockPriceDate: '2004-08-19',
    lastStockPriceDate: '2024-07-10',
    legacySector: 'Technology',
    legacyIndustryCategory: 'Internet',
    legacyIndustryGroup: 'Web Services',
    mosaicPositioning: {
      defaultVisible: true,
      initialOrder: 4,
      zIndex: 7,
    },
  },
  TSLA: {
    ticker: 'TSLA',
    name: 'Tesla, Inc.',
    legalName: 'Tesla, Inc.',
    stockExchange: 'Nasdaq',
    shortDescription: 'Tesla designs electric vehicles and energy storage systems.',
    longDescription:
      'Tesla designs and manufactures electric vehicles, solar products, and energy storage solutions. It also operates Supercharger stations worldwide.',
    web: 'tesla.com',
    businessAddress: '3500 Deer Creek Road, Palo Alto, CA, 94304',
    businessPhone: '(650) 681-5000',
    entityLegalForm: 'INCORPORATED',
    latestFilingDate: '2024-05-15',
    incCountry: 'USA',
    employees: 70000,
    sector: 'Consumer Cyclical',
    industryCategory: 'Automobiles',
    industryGroup: 'Electric Vehicles',
    firstStockPriceDate: '2010-06-29',
    lastStockPriceDate: '2024-07-30',
    legacySector: 'Consumer Goods',
    legacyIndustryCategory: 'Automotive',
    legacyIndustryGroup: 'Electric Cars',
    mosaicPositioning: {
      defaultVisible: true,
      initialOrder: 5,
      zIndex: 6,
    },
  },
  AMZN: {
    ticker: 'AMZN',
    name: 'Amazon.com, Inc.',
    legalName: 'Amazon.com, Inc.',
    stockExchange: 'Nasdaq',
    shortDescription: 'Amazon is an online retailer and cloud services provider.',
    longDescription:
      'Amazon operates the largest e-commerce platform in the world and provides cloud services through AWS. It also produces consumer electronics and offers subscription services.',
    web: 'amazon.com',
    businessAddress: '410 Terry Avenue North, Seattle, WA, 98109',
    businessPhone: '(206) 266-1000',
    entityLegalForm: 'INCORPORATED',
    latestFilingDate: '2024-04-25',
    incCountry: 'USA',
    employees: 1608000,
    sector: 'Consumer Cyclical',
    industryCategory: 'Retail',
    industryGroup: 'E-commerce',
    firstStockPriceDate: '1997-05-15',
    lastStockPriceDate: '2024-06-30',
    legacySector: 'Consumer Services',
    legacyIndustryCategory: 'Internet Retail',
    legacyIndustryGroup: 'E-commerce',
    mosaicPositioning: {
      defaultVisible: true,
      initialOrder: 6,
      zIndex: 5,
    },
  },
  FB: {
    ticker: 'FB',
    name: 'Meta Platforms, Inc.',
    legalName: 'Meta Platforms, Inc.',
    stockExchange: 'Nasdaq',
    shortDescription: 'Meta is the parent company of Facebook, Instagram, and WhatsApp.',
    longDescription:
      'Meta connects people through social media platforms like Facebook, Instagram, and WhatsApp. It also develops virtual reality hardware and software.',
    web: 'meta.com',
    businessAddress: '1 Hacker Way, Menlo Park, CA, 94025',
    businessPhone: '(650) 543-4800',
    entityLegalForm: 'INCORPORATED',
    latestFilingDate: '2024-03-30',
    incCountry: 'USA',
    employees: 77000,
    sector: 'Communication Services',
    industryCategory: 'Interactive Media',
    industryGroup: 'Social Media',
    firstStockPriceDate: '2012-05-18',
    lastStockPriceDate: '2024-07-25',
    legacySector: 'Technology',
    legacyIndustryCategory: 'Social Networks',
    legacyIndustryGroup: 'Social Media Platforms',
    mosaicPositioning: {
      defaultVisible: true,
      initialOrder: 7,
      zIndex: 4,
    },
  },
  DIS: {
    ticker: 'DIS',
    name: 'The Walt Disney Company',
    legalName: 'The Walt Disney Company',
    stockExchange: 'NYSE',
    shortDescription: 'Disney creates entertainment content and operates theme parks.',
    longDescription:
      'Disney is a multinational entertainment company known for creating animated movies, theme parks, and consumer products.',
    web: 'disney.com',
    businessAddress: '500 S. Buckskin Dr., Burbank, CA, 91521',
    businessPhone: '(818) 560-1000',
    entityLegalForm: 'INCORPORATED',
    latestFilingDate: '2024-05-01',
    incCountry: 'USA',
    employees: 223000,
    sector: 'Communication Services',
    industryCategory: 'Entertainment',
    industryGroup: 'Media Networks',
    firstStockPriceDate: '1957-11-12',
    lastStockPriceDate: '2024-08-01',
    legacySector: 'Entertainment',
    legacyIndustryCategory: 'Movies',
    legacyIndustryGroup: 'Entertainment',
    mosaicPositioning: {
      defaultVisible: true,
      initialOrder: 8,
      zIndex: 3,
    },
  },
  BABA: {
    ticker: 'BABA',
    name: 'Alibaba Group Holding Ltd.',
    legalName: 'Alibaba Group Holding Ltd.',
    stockExchange: 'NYSE',
    shortDescription: 'Alibaba is a Chinese e-commerce and technology conglomerate.',
    longDescription:
      'Alibaba operates the world’s largest online and mobile commerce company and provides services in cloud computing and digital entertainment.',
    web: 'alibaba.com',
    businessAddress: '969 West Wen Yi Road, Hangzhou, Zhejiang, 311121',
    businessPhone: '+86 571-8502-2088',
    entityLegalForm: 'LIMITED LIABILITY COMPANY',
    latestFilingDate: '2024-06-15',
    incCountry: 'China',
    employees: 251000,
    sector: 'Consumer Cyclical',
    industryCategory: 'E-commerce',
    industryGroup: 'Retailing',
    firstStockPriceDate: '2014-09-19',
    lastStockPriceDate: '2024-07-12',
    legacySector: 'Consumer Services',
    legacyIndustryCategory: 'Internet Retail',
    legacyIndustryGroup: 'E-commerce',
    mosaicPositioning: {
      defaultVisible: true,
      initialOrder: 9,
      zIndex: 2,
    },
  },
  PEP: {
    ticker: 'PEP',
    name: 'PepsiCo, Inc.',
    legalName: 'PepsiCo, Inc.',
    stockExchange: 'Nasdaq',
    shortDescription: 'PepsiCo is a multinational food and beverage company.',
    longDescription:
      'PepsiCo produces and markets food and beverages, including well-known brands such as Pepsi, Mountain Dew, Gatorade, Tropicana, and Lay’s.',
    web: 'pepsico.com',
    businessAddress: '700 Anderson Hill Road, Purchase, NY, 10577',
    businessPhone: '(914) 253-2000',
    entityLegalForm: 'INCORPORATED',
    latestFilingDate: '2024-04-10',
    incCountry: 'USA',
    employees: 291000,
    sector: 'Consumer Defensive',
    industryCategory: 'Beverages',
    industryGroup: 'Soft Drinks',
    firstStockPriceDate: '1965-03-01',
    lastStockPriceDate: '2024-06-20',
    legacySector: 'Consumer Goods',
    legacyIndustryCategory: 'Food and Beverages',
    legacyIndustryGroup: 'Beverages',
    mosaicPositioning: {
      defaultVisible: true,
      initialOrder: 10,
      zIndex: 1,
    },
  },
};
